### ISSUE TITLE
글 열면 1초 후 crash

### ISSUE THREAD

**Issue by JellyBrick** [organization/OpenDC#2]
`GeckoView` 관련 문제인 것으로 보임

# Stacktrace
stacktrace 없음

**Comment by JellyBrick** [comment]
캐시 삭제후, 새로 빌드하니 발생한 오류입니다.
# Logcat
```
E/GeckoLoader: Load diagnostics: LOAD mozglue: ABI: unknown (0x0), arm64-v8a: Data: /data/user/0/be.zvz.opendc, ax=false, ddx=false, -1x=false, -2x=false, nativeLib: /data/app/be.zvz.opendc-TjeHGd_XytUNH4EZYrujhA==/lib/arm64, dirx=false, libx=false
E/AndroidRuntime: FATAL EXCEPTION: Gecko
    Process: be.zvz.opendc, PID: 1747
    java.lang.RuntimeException: LOAD mozglue: ABI: unknown (0x0), arm64-v8a: Data: /data/user/0/be.zvz.opendc, ax=false, ddx=false, -1x=false, -2x=false, nativeLib: /data/app/be.zvz.opendc-TjeHGd_XytUNH4EZYrujhA==/lib/arm64, dirx=false, libx=false
        at org.mozilla.gecko.mozglue.GeckoLoader.doLoadLibrary(GeckoLoader.java:464)
        at org.mozilla.gecko.mozglue.GeckoLoader.loadMozGlue(GeckoLoader.java:472)
        at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:443)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/be.zvz.opendc-TjeHGd_XytUNH4EZYrujhA==/base.apk"],nativeLibraryDirectories=[/data/app/be.zvz.opendc-TjeHGd_XytUNH4EZYrujhA==/lib/arm64, /system/lib64]]] couldn't find "libmozglue.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.mozilla.gecko.mozglue.GeckoLoader.doLoadLibraryExpected(GeckoLoader.java:385)
        at org.mozilla.gecko.mozglue.GeckoLoader.doLoadLibrary(GeckoLoader.java:411)
        at org.mozilla.gecko.mozglue.GeckoLoader.loadMozGlue(GeckoLoader.java:472) 
        at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:443) 
```

**Comment by JellyBrick** [comment]
```kotlin
val runtime = GeckoRuntime.getDefault(this)
```
에서 세그멘테이션 오류가 발생하는 것으로 보입니다.

# Logcat

```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 4414 (Gecko), pid 4144 (be.zvz.opendc)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG: backtrace:
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #00 pc 00000000018614c0  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #01 pc 00000000028806e4  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #02 pc 00000000028f7e28  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #03 pc 000000000235555c  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #04 pc 00000000024138a0  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #05 pc 0000000002d29c20  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #06 pc 0000000002e12e3c  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #07 pc 0000000002d2b104  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #08 pc 0000000002d213e0  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #09 pc 00000000024136a0  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #10 pc 0000000002d29f58  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #11 pc 0000000002d4006c  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #12 pc 0000000002d4029c  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #13 pc 0000000002d401e8  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #14 pc 000000000273ed74  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #15 pc 000000000274055c  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #16 pc 0000000002896e70  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #17 pc 00000000024138a0  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #18 pc 0000000002d29c20  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #19 pc 00000000024539a0  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.603 11011-11011/? A/DEBUG:       #20 pc 0000000002413428  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #21 pc 00000000024185f8  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #22 pc 0000000002d244d8  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #23 pc 00000000024136a0  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #24 pc 00000000024139f8  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #25 pc 00000000024273fc  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #26 pc 00000000022dd100  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #27 pc 00000000025aaf0c  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #28 pc 000000000387bc28  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #29 pc 0000000002cdfd80  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #30 pc 0000000002cde34c  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #31 pc 00000000020078e8  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #32 pc 0000000002cdfb70  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libxul.so (GeckoStart+104) (BuildId: 072369ae0ba7fb88ebcef1d0b4328d337a3bcde5)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #33 pc 0000000000070854  /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/lib/arm64/libmozglue.so (Java_org_mozilla_gecko_mozglue_GeckoLoader_nativeRun+444) (BuildId: cb36d71c02dc01e1a1de30e3f9e957198148dc01)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #34 pc 0000000000140350  /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #35 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #36 pc 00000000001460cc  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #37 pc 00000000002e3be8  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #38 pc 00000000002dfce0  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+656) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #39 pc 00000000005a81ac  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStaticRange+236) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #40 pc 0000000000131c94  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static_range+20) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #41 pc 00000000000e0d34  [anon:dalvik-classes3.dex extracted in memory from /data/app/be.zvz.opendc-EhIm4RzPg2tE7unu3sV1kQ==/base.apk!classes3.dex] (org.mozilla.gecko.GeckoThread.run+548)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #42 pc 00000000002b4518  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.14549768435847923494+240) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #43 pc 0000000000593c38  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1024) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #44 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #45 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.604 11011-11011/? A/DEBUG:       #46 pc 00000000001460ac  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.605 11011-11011/? A/DEBUG:       #47 pc 00000000004b2aa0  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.605 11011-11011/? A/DEBUG:       #48 pc 00000000004b3b50  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.605 11011-11011/? A/DEBUG:       #49 pc 00000000004f4600  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176) (BuildId: f84f814c1ec5f0baecf913aa12aa71e3)
2020-01-10 05:52:41.605 11011-11011/? A/DEBUG:       #50 pc 00000000000e3b14  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 220051b49364b1c2da3adf10c30832cc)
2020-01-10 05:52:41.605 11011-11011/? A/DEBUG:       #51 pc 0000000000085330  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 220051b49364b1c2da3adf10c30832cc)
```

**Comment by JellyBrick** [comment]
GeckoView 대신 WebViewSuite 사용해서 해결
